variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_windows:
  stage: build
  script:
    - chcp 65001
    - yarn build:prod
    - curl -v --user devops:UaW9URs9KQlYtFz3 -T ./out/setup/{package-info.json,vc-desktop-%CI_COMMIT_TAG%.exe} https://nexus.yealinkops.com/repository/packages-manager/client_module/vcd-h5/%CI_COMMIT_TAG%/windows/
  only:
    - tags
#  artifacts:
#    name: $CI_JOB_NAME
#    paths:
#      - out/setup/
  cache:
    paths:
    - node_modules/
  tags:
    - win10_233

build_linux:
  stage: build
  script:
    - yarn build:prod
    - curl -v -u devops:UaW9URs9KQlYtFz3 -T "./out/setup/{package-info.json,vc-desktop-$CI_COMMIT_TAG.AppImage}" https://nexus.yealinkops.com/repository/packages-manager/client_module/vcd-h5/$CI_COMMIT_TAG/linux/
  only:
    - tags
  cache:
    paths:
    - node_modules/
  tags:
    - centos7.5_231

build_macos:
  stage: build
  script:
    - yarn build:prod
    - curl -v -u devops:UaW9URs9KQlYtFz3 -T "./out/setup/{package-info.json,vc-desktop-$CI_COMMIT_TAG.dmg}" https://nexus.yealinkops.com/repository/packages-manager/client_module/vcd-h5/$CI_COMMIT_TAG/macos/
  only:
    - tags
  cache:
    paths:
    - node_modules/
  tags:
    - macos_232