variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  stage: build
  script:
    - chcp 65001
    - yarn build:prod
  only:
    - tags
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - out/setup/
  cache:
    paths:
    - node_modules/
  tags:
    - win10_233