variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build_windows:
  stage: build
  script:
    - chcp 65001
    - yarn build:prod
  only:
    - tags
#  artifacts:
#    name: $CI_JOB_NAME
#    paths:
#      - out/setup/
  cache:
    paths:
    - node_modules/
  tags:
    - win10_233

build_linux:
  stage: build
  script:
    - yarn build:prod
  only:
    - tags
  cache:
    paths:
    - node_modules/
  tags:
    - centos7.5_231

build_macos:
  stage: build
  script:
    - yarn build:prod
  only:
    - tags
  cache:
    paths:
    - node_modules/
  tags:
    - macos_232