export const LOGIN_STORAGE = {
  SERVER_TYPE               : 'SERVER_TYPE',
  REMEMBER_PASSWORD         : 'REMEMBER_PASSWORD',
  AUTO_LOGIN                : 'AUTO_LOGIN',
  AUTO_LOGIN_DISABLED       : 'AUTO_LOGIN_DISABLED',
  ACCOUNT_LIST              : 'ACCOUNT_LIST',
  MEETING_ACCOUNT_LIST      : 'MEETING_ACCOUNT_LIST',
  ANON_MEETING_ACCOUNT_LIST : 'ANON_MEETING_ACCOUNT_LIST',
  FIRST_START               : 'FIRST_START',
};

export const CONTACT_STORAGE = {
  LOCAL_CONTACT : 'LOCAL_CONTACT',
};

export const SETTING_STORAGE = {
  SETTING : 'APP_SETTING',
};
